name: draft

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
        with:
          fetch-depth: 0

      - uses: softprops/action-gh-release@v1
        with:
          draft: true
          tag_name: master
          target_commitish: master
          generate_release_notes: true
          name: DRAFT
